name: pusher_client_socket
description: "The pusher client using websocket client [available for all platforms]"
version: 0.0.7
homepage: https://github.com/AbdoPrDZ/pusher_client_socket

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  meta: ^1.16.0
  pinenacl: ^0.6.0
  web_socket_client: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: null
